[env:cyd]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = partitions.csv
monitor_speed = 115200
lib_deps =
  bodmer/TFT_eSPI@^2.5.43
  https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
  bodmer/TJpg_Decoder@^1.1.0
  bblanchon/ArduinoJson@^7.0.0
build_flags =
  -D USER_SETUP_LOADED=1
  -D ILI9341_2_DRIVER=1
  -D TFT_WIDTH=240
  -D TFT_HEIGHT=320
  -D TFT_MISO=12
  -D TFT_MOSI=13
  -D TFT_SCLK=14
  -D TFT_CS=15
  -D TFT_DC=2
  -D TFT_RST=4
  -D TFT_BL=21
  -D TOUCH_CS=33
  -D SPI_FREQUENCY=55000000
  -D SPI_TOUCH_FREQUENCY=2500000
  -D LOAD_GLCD=1
  -D LOAD_FONT2=1
  -D LOAD_FONT4=1
  -D LOAD_GFXFF=1
  -D SMOOTH_FONT=1
  -D SUPPORT_TRANSACTIONS=1
